site_name: Мое портфолио по программированию
site_description: Отчетные работы по курсу программирования
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections

nav:
  - Главная: index.md
  - Работы:
      - Работа 1. "two_sum": work1.md
      - Работа 2. "division_test": work2.md
      - Работа 3. "binary_tree": work3.md
      - Работа 4. "iterators_generators": work4.md
      - Работа 5. "decorator_pattern": work5.md
      - Работа 6. "singleton_pattern": work6.md
      - Работа 7. "state_pattern": work7.md
      - Работа 8. "OOP_python": work8.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences